version: '3'
services:
  resource-scheduler:
    build: .
    ports:
      - "127.0.0.1:80:8080"
    depends_on: 
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "127.0.0.1:27017:27017"